### ISSUE TITLE
remoteTagList failed on watch

### ISSUE THREAD

**Issue by enuggetry** [sakshamsaxena/sails-hook-jbvcs#22]
Ran into this bug.  Seems to happen on the 2nd iteration.

```
[root@localhost sails-hook-jbvcs]# jbvcs -u enuggetry -r jbvcs-test -w 1000 0   Checking API ...
API is up.

Checking Repo ...
Repo found.

Cloning Tags ...
Cloning v0.0.1 into /var/www/jbrowse/versions/jbvcs-test/v0.0.1 ...
Cloned v0.0.1
volvox-sorted.bam.coverage.bw
volvox-sorted.bam
[ { extension: 'bam',
    path: '/data_files/volvox-paired.bam',
    build: 'bin/add-bam-track.pl',
    opts: '--label jbvcs-test-v0.0.1-BAM  --in versions/jbvcs-test/v0.0.1/trackList.json --bam_url .' },
  { extension: 'bam',
    path: '/data_files/volvox-sorted.bam',
    build: 'bin/add-bam-track.pl',
    opts: '--label jbvcs-test-v0.0.1-BAM-Sorted  --in versions/jbvcs-test/v0.0.1/trackList.json --bam_url .' },
  { extension: 'bam',
    path: '/data_files/volvox-sorted.bam',
    build: 'bin/add-bam-track.pl',
    opts: '--label jbvcs-test-v0.0.1-BAM-Coverage --coverage --min_score 0 --max_score 40  --in versions/jbvcs-test/v0.0.1/trackList.json --bam_url .' },
  { extension: 'gff3',
    path: './versions/jbvcs-test/v0.0.1/data_files/volvox.gff3',
    build: 'bin/flatfile-to-json.pl',
    opts: '--trackType \'CanvasFeatures\' --trackLabel jbvcs-test-v0.0.1-GFF  --gff ' },
  { extension: 'fa',
    path: './versions/jbvcs-test/v0.0.1/data_files/volvox.fa',
    build: 'bin/prepare-refseqs.pl',
    opts: '--fasta ' } ]
Building  fa
Building  gff3
Building  bam
cd /var/www/jbrowse/ && bin/add-bam-track.pl --label jbvcs-test-v0.0.1-BAM-Coverage --coverage --min_score 0 --max_score 40  --in versions/jbvcs-test/v0.0.1/trackList.json --bam_url ./data_files/volvox-sorted.bam --out versions/jbvcs-test/v0.0.1/trackList.json
Building  bam
cd /var/www/jbrowse/ && bin/add-bam-track.pl --label jbvcs-test-v0.0.1-BAM-Sorted  --in versions/jbvcs-test/v0.0.1/trackList.json --bam_url ./data_files/volvox-sorted.bam --out versions/jbvcs-test/v0.0.1/trackList.json
Building  bam
cd /var/www/jbrowse/ && bin/add-bam-track.pl --label jbvcs-test-v0.0.1-BAM  --in versions/jbvcs-test/v0.0.1/trackList.json --bam_url ./data_files/volvox-paired.bam --out versions/jbvcs-test/v0.0.1/trackList.json
Done!
Watching remote repo for changes now ...
/usr/local/lib/node_modules/sails-hook-jbvcs/lib/cli.js:132
                var currentTag = ((configData.remoteTagList)[0]).name;
                                             ^

TypeError: Cannot read property 'remoteTagList' of null
    at Timeout._repeat (/usr/local/lib/node_modules/sails-hook-jbvcs/lib/cli.js:132:32)
    at Timeout.wrapper [as _onTimeout] (timers.js:425:11)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[root@localhost sails-hook-jbvcs]#

```

**Comment by sakshamsaxena** [comment]
I'll look into this asap.
