### ISSUE TITLE
jbvcs watch fails if prior version exists.

### ISSUE THREAD

**Issue by enuggetry** [sakshamsaxena/sails-hook-jbvcs#24]
Ran it a 2nd time and it failed right away. 
It should detect whether the version exists and ignore if it does.

```
[root@localhost jbrowse]# jbvcs -u enuggetry -r jbvcs-test -w 1000 0
Checking API ...
API is up.

Checking Repo ...
Repo found.

Cloning Tags ...
Cloning v0.0.1 into /var/www/jbrowse/versions/jbvcs-test/v0.0.1 ...
/usr/local/lib/node_modules/sails-hook-jbvcs/lib/index.js:32
                        if (error) throw new Error(error.message);
                                   ^

Error: Command failed: git clone -b "v0.0.1" https://github.com/enuggetry/jbvcs-test.git /var/www/jbrowse/versions/jbvcs-test/v0.0.1
fatal: destination path '/var/www/jbrowse/versions/jbvcs-test/v0.0.1' already exists and is not an empty directory.

    at exec (/usr/local/lib/node_modules/sails-hook-jbvcs/lib/index.js:32:21)
    at ChildProcess.exithandler (child_process.js:213:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
[root@localhost jbrowse]#


```

**Comment by sakshamsaxena** [comment]
It was ideally meant to run just once, and then the watcher would continue to pull latest tags without re running this. But I see your point.

**Comment by sakshamsaxena** [comment]
To test the code solely, you can run the tests. They clean up after cloning, so they're ideal to test if the operations are being performed smoothly or not.
